title: Paul Martin
url: "https://PaulsBitsAndBytes.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

use_tracking: yes  # https://notpaul.goatcounter.com/

footer: no
footer_url: "https://github.com/notpaulmartin"
footer_text: "Page based on the researcher template for Jekyll"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "https://raw.githubusercontent.com/notpaulmartin/CV/main/cv_pmartin.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Photos"
   link: "photos"
